// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA06DDX5bmsyf1pCoQOpgjlyJ6r9MyAAG0',
    appId: '1:242177661490:web:2d78275a182285e61bfa2b',
    messagingSenderId: '242177661490',
    projectId: 'usecasepointtool',
    authDomain: 'usecasepointtool.firebaseapp.com',
    storageBucket: 'usecasepointtool.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2PGw3mtw3f2IpKh5rE-Bbrzg69_Nuyg',
    appId: '1:242177661490:android:56857ab3c13c4d321bfa2b',
    messagingSenderId: '242177661490',
    projectId: 'usecasepointtool',
    storageBucket: 'usecasepointtool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjGtykLGa8Eq-hmuMO7vfsNMNkppYBOc0',
    appId: '1:242177661490:ios:85855614f96ad3ea1bfa2b',
    messagingSenderId: '242177661490',
    projectId: 'usecasepointtool',
    storageBucket: 'usecasepointtool.appspot.com',
    iosClientId: '242177661490-26o0k2riaias8n2gg1rp6gepoq5e3gfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.usecasepointstool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjGtykLGa8Eq-hmuMO7vfsNMNkppYBOc0',
    appId: '1:242177661490:ios:85855614f96ad3ea1bfa2b',
    messagingSenderId: '242177661490',
    projectId: 'usecasepointtool',
    storageBucket: 'usecasepointtool.appspot.com',
    iosClientId: '242177661490-26o0k2riaias8n2gg1rp6gepoq5e3gfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.usecasepointstool',
  );
}
